// <auto-generated />
using System;
using LibSys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibSys.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240107122432_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibSys.Models.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookDefinitionId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b61bcd3-8c89-4c6e-bbd6-f983861c0a98"),
                            BookDefinitionId = new Guid("7132bc9d-aec5-419a-8594-a427b49a0393"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("6c3cc738-65cc-4c63-9cfd-8bdcae010a84"),
                            BookDefinitionId = new Guid("4f15eadc-b2e9-4ac8-b7c5-af8f383105ef"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("21c536c4-494c-44f1-84c5-be8fe6145b58"),
                            BookDefinitionId = new Guid("c687f724-506d-448b-9511-e686b91f3dda"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d3e80909-4838-4a08-bf68-917e7d5de7af"),
                            BookDefinitionId = new Guid("08c709c9-0d6e-4c5c-9b91-77f039dfdb51"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("a4263179-198f-471a-b7f5-747e2aa05c50"),
                            BookDefinitionId = new Guid("01ac681a-b52e-45cb-8b81-182d1cda3520"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("428d8f2a-4f09-4f20-bff6-cd9de70e8204"),
                            BookDefinitionId = new Guid("7cc4c6a6-cbab-4105-a8a6-c100e5c85d67"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("9aa721a3-8746-43c9-b1eb-6476d2dacacc"),
                            BookDefinitionId = new Guid("37d737e5-6bc1-40a2-a8c6-b34564d48412"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("ec8deff1-7591-4845-920a-2cafb3d5c461"),
                            BookDefinitionId = new Guid("01ac681a-b52e-45cb-8b81-182d1cda3520"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e20c0a42-43ce-4271-a01f-9935df0aa371"),
                            BookDefinitionId = new Guid("2eb18b3a-eb70-4984-b20e-eba3082dd5c3"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("7748142b-c549-45af-b7e9-7857acf63d63"),
                            BookDefinitionId = new Guid("80ef7321-b0a3-4453-b1ba-6e3ecf1b0d0e"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b0572f4e-2e8d-41d8-8bb1-3711f72a58a8"),
                            BookDefinitionId = new Guid("80ef7321-b0a3-4453-b1ba-6e3ecf1b0d0e"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("217e2ead-b9de-4a38-a2ab-995f9515a8b7"),
                            BookDefinitionId = new Guid("01ac681a-b52e-45cb-8b81-182d1cda3520"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("73d4d398-6788-4b58-87ff-dfdc5b977dc9"),
                            BookDefinitionId = new Guid("4f15eadc-b2e9-4ac8-b7c5-af8f383105ef"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("20ec3e8b-8c3b-4dee-9da7-093579c71a4f"),
                            BookDefinitionId = new Guid("7cc4c6a6-cbab-4105-a8a6-c100e5c85d67"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("4c2cbb8e-f1b7-4bc8-b5b6-0b64a62ae510"),
                            BookDefinitionId = new Guid("bcecb84c-9f01-4325-b721-9326fb96f2d7"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("85c515c7-3ae7-4845-b5ab-043eb413bd22"),
                            BookDefinitionId = new Guid("ff1ead80-59eb-4049-b0f8-a71d3911dbd5"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("fb6d47ec-fa02-4573-a76d-daba68e75860"),
                            BookDefinitionId = new Guid("c687f724-506d-448b-9511-e686b91f3dda"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("461e28c6-ed59-4055-80a7-a34730a367ba"),
                            BookDefinitionId = new Guid("0d0f72a9-d358-4283-aca5-15811ed0aeb8"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a26434dd-0bce-44c6-b47d-7fa81425e9a6"),
                            BookDefinitionId = new Guid("512a64d4-2940-4897-b202-cb519ece9f19"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("1102a15c-bc66-4291-ac12-8069ef385393"),
                            BookDefinitionId = new Guid("8710dd3c-1f39-4f82-80ee-b098c7c5b3c1"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("68dd801b-29a6-49e0-9615-1116b02d4f29"),
                            BookDefinitionId = new Guid("8aa0f520-e3aa-4838-b4b8-54b3fda386a3"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3df99c7e-dc10-420d-ac5c-9547f930c9bc"),
                            BookDefinitionId = new Guid("e1a08da5-0c3e-4f4c-8f75-3fde7ef6c9b7"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("cf817901-5d82-4394-ba7c-f89466bf2384"),
                            BookDefinitionId = new Guid("baff91b9-a58d-4e3c-a938-3fd293b432ed"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d8cd43f1-c23f-4a5c-98d6-ab2ffd9ac952"),
                            BookDefinitionId = new Guid("2ba37673-a6e9-4539-9f68-24921544db84"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("706c489e-ba97-47d9-b65b-1c131a39acab"),
                            BookDefinitionId = new Guid("8aa0f520-e3aa-4838-b4b8-54b3fda386a3"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("818d1105-03f3-4ea0-adcd-516f3f413842"),
                            BookDefinitionId = new Guid("e1a08da5-0c3e-4f4c-8f75-3fde7ef6c9b7"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("78587f17-5dec-4ae4-b4f0-216b0e1866ed"),
                            BookDefinitionId = new Guid("80ef7321-b0a3-4453-b1ba-6e3ecf1b0d0e"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("7a0a4ec2-dad5-41e5-9702-0b942b0043dd"),
                            BookDefinitionId = new Guid("a2d0d869-69bb-4d53-8873-25cad510338b"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bda065a6-57f6-4a7e-9d8e-5a976fa1d57f"),
                            BookDefinitionId = new Guid("7132bc9d-aec5-419a-8594-a427b49a0393"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("522672d0-5c49-45a0-8533-142c81cfe905"),
                            BookDefinitionId = new Guid("0d0f72a9-d358-4283-aca5-15811ed0aeb8"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("97fd701a-3ea5-4420-be7d-0f0d00f31958"),
                            BookDefinitionId = new Guid("c687f724-506d-448b-9511-e686b91f3dda"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("57650987-400b-4a05-9314-472676a3e68f"),
                            BookDefinitionId = new Guid("ff1ead80-59eb-4049-b0f8-a71d3911dbd5"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e936176e-a4f6-43d4-a060-7e164013496d"),
                            BookDefinitionId = new Guid("7cc4c6a6-cbab-4105-a8a6-c100e5c85d67"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("e29817aa-3989-4831-903b-450f638e174e"),
                            BookDefinitionId = new Guid("a2d0d869-69bb-4d53-8873-25cad510338b"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("80c3cac4-9b75-431f-93dd-12b3e480281d"),
                            BookDefinitionId = new Guid("bcecb84c-9f01-4325-b721-9326fb96f2d7"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("ab9d7520-8bdc-4e8a-8e1c-597d8678b846"),
                            BookDefinitionId = new Guid("e1a08da5-0c3e-4f4c-8f75-3fde7ef6c9b7"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8e956fed-01da-421c-8ea4-790d0c14bffa"),
                            BookDefinitionId = new Guid("b6fda587-5512-4ccc-9294-5e52c7390773"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("687f20d1-fcb5-40d4-8261-96469633348a"),
                            BookDefinitionId = new Guid("7cc4c6a6-cbab-4105-a8a6-c100e5c85d67"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("19a2c0cf-b56a-4cc6-9d55-cce66a648bd2"),
                            BookDefinitionId = new Guid("4f15eadc-b2e9-4ac8-b7c5-af8f383105ef"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("42aae123-5f81-439c-b85c-86b194f5ac84"),
                            BookDefinitionId = new Guid("a2d0d869-69bb-4d53-8873-25cad510338b"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("874c32cd-7e95-479e-b709-c044b3a43896"),
                            BookDefinitionId = new Guid("0a097611-ce71-4a35-8b70-e3e855a70ae7"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a908b462-f860-42eb-aba6-f1cbbaab0989"),
                            BookDefinitionId = new Guid("326b3b91-ecd4-48bd-bddb-3fd788d6ea6a"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("b2d99989-50e6-4a17-a9ae-a7480e127f53"),
                            BookDefinitionId = new Guid("37d737e5-6bc1-40a2-a8c6-b34564d48412"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("079638cb-6d07-4ad6-963f-56cfccee80c7"),
                            BookDefinitionId = new Guid("baff91b9-a58d-4e3c-a938-3fd293b432ed"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("e8321ee2-91dd-470f-aba4-6d3195d24b1a"),
                            BookDefinitionId = new Guid("08c709c9-0d6e-4c5c-9b91-77f039dfdb51"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("d2159c46-4ed0-492f-b189-d16d28cac813"),
                            BookDefinitionId = new Guid("bcecb84c-9f01-4325-b721-9326fb96f2d7"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("98ddb6e6-db0b-4066-8ac6-d84b0453856a"),
                            BookDefinitionId = new Guid("0a097611-ce71-4a35-8b70-e3e855a70ae7"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d6967918-e933-4539-9bdf-0abe2d95b0a7"),
                            BookDefinitionId = new Guid("0d0f72a9-d358-4283-aca5-15811ed0aeb8"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("77d2ebd2-1446-448f-8099-4a45f20f0ffb"),
                            BookDefinitionId = new Guid("80ef7321-b0a3-4453-b1ba-6e3ecf1b0d0e"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8600bd80-5d2f-4a26-93c9-8ad950b4f87e"),
                            BookDefinitionId = new Guid("08c709c9-0d6e-4c5c-9b91-77f039dfdb51"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("f2adcd4e-f13c-4dfd-84e9-f4da752a3e05"),
                            BookDefinitionId = new Guid("2eb18b3a-eb70-4984-b20e-eba3082dd5c3"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5d7826ed-31e5-4ae8-93f4-ebd17dd2ff53"),
                            BookDefinitionId = new Guid("0d0f72a9-d358-4283-aca5-15811ed0aeb8"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("eac4e213-434d-4dd1-ae8d-90b4cd8a4b7f"),
                            BookDefinitionId = new Guid("08c709c9-0d6e-4c5c-9b91-77f039dfdb51"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f46924fb-f28f-4374-8175-3f50ee53edb3"),
                            BookDefinitionId = new Guid("18b3eeac-a9e1-4098-a094-d9cf9df885df"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("fad3d981-ae34-4af0-8458-f0a9b1dcfc30"),
                            BookDefinitionId = new Guid("2ba37673-a6e9-4539-9f68-24921544db84"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("740f47fe-fd84-4362-aeee-0466b0361aa9"),
                            BookDefinitionId = new Guid("326b3b91-ecd4-48bd-bddb-3fd788d6ea6a"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1ca457bb-65a3-4368-87a7-cfb4c60fb149"),
                            BookDefinitionId = new Guid("7921061d-840c-4a56-8b1f-841f7390edc8"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("b0c59b6f-3213-4ce4-adc6-f8450208d0ab"),
                            BookDefinitionId = new Guid("2ba37673-a6e9-4539-9f68-24921544db84"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3273742c-d607-4b81-ae55-3d65b3941f9c"),
                            BookDefinitionId = new Guid("cf5c7384-0cac-448b-bec1-c4f3eb3769f0"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("b64e0711-4ac0-4cf9-aa4d-9e5d2e6167ac"),
                            BookDefinitionId = new Guid("8710dd3c-1f39-4f82-80ee-b098c7c5b3c1"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("a77ab981-9426-40c4-8289-735bdca7ef3f"),
                            BookDefinitionId = new Guid("b6fda587-5512-4ccc-9294-5e52c7390773"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("77b9510b-5310-4a1f-b5ad-3b310fc432ea"),
                            BookDefinitionId = new Guid("512a64d4-2940-4897-b202-cb519ece9f19"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("435579ed-f57d-45d5-bfc2-41aeaa03b0bc"),
                            BookDefinitionId = new Guid("8aa0f520-e3aa-4838-b4b8-54b3fda386a3"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5694a295-f5ea-46ec-bd54-8f625aa4707c"),
                            BookDefinitionId = new Guid("4d25c8c0-e068-40c7-b316-6acba16c261d"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("f6cdb6ed-9555-46ba-b8d1-c548c2c9e0ab"),
                            BookDefinitionId = new Guid("b7d20548-b9fa-4ffe-9166-5b42308864a1"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("69a4237b-f0f7-46f3-84c7-08893d583391"),
                            BookDefinitionId = new Guid("b6fda587-5512-4ccc-9294-5e52c7390773"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("4746d247-4e52-40e2-8d46-e9c97fd9748d"),
                            BookDefinitionId = new Guid("7921061d-840c-4a56-8b1f-841f7390edc8"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("16aa5a85-50e6-4b37-b310-1ca8ffabd155"),
                            BookDefinitionId = new Guid("37d737e5-6bc1-40a2-a8c6-b34564d48412"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("872ff021-0db3-4d31-be94-58d48b8be986"),
                            BookDefinitionId = new Guid("08c709c9-0d6e-4c5c-9b91-77f039dfdb51"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("29a2798b-2d43-429c-b232-704e0e42a61e"),
                            BookDefinitionId = new Guid("7921061d-840c-4a56-8b1f-841f7390edc8"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("28e868af-842e-43f2-8a45-447f8e14031c"),
                            BookDefinitionId = new Guid("7921061d-840c-4a56-8b1f-841f7390edc8"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("86a88a4e-d4aa-44c7-9a56-e0253efc60fc"),
                            BookDefinitionId = new Guid("a5856006-2bac-42d3-a60c-cb5f39715a19"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d91ae0ee-5b54-43cb-8070-1b8da1b3175c"),
                            BookDefinitionId = new Guid("326b3b91-ecd4-48bd-bddb-3fd788d6ea6a"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bbc5b71a-f9c8-4bc4-928e-7cf043fbcac5"),
                            BookDefinitionId = new Guid("18b3eeac-a9e1-4098-a094-d9cf9df885df"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("812d4f76-5d7e-4801-bb46-826f0521fa65"),
                            BookDefinitionId = new Guid("08c709c9-0d6e-4c5c-9b91-77f039dfdb51"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e8d38cf2-f461-46e8-a4b2-6582436ec489"),
                            BookDefinitionId = new Guid("e1a08da5-0c3e-4f4c-8f75-3fde7ef6c9b7"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("4d2cc9be-bb09-44ed-9f37-0e9ef3466926"),
                            BookDefinitionId = new Guid("bcecb84c-9f01-4325-b721-9326fb96f2d7"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9a42a451-c4a1-4a6c-934a-3ad5315b0bc8"),
                            BookDefinitionId = new Guid("4d25c8c0-e068-40c7-b316-6acba16c261d"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("b9bc4d99-c0a1-4a67-85f8-b276d406b8f9"),
                            BookDefinitionId = new Guid("2eb18b3a-eb70-4984-b20e-eba3082dd5c3"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("a404267e-8bbf-4d7c-a099-35583479fefa"),
                            BookDefinitionId = new Guid("b7d20548-b9fa-4ffe-9166-5b42308864a1"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("9cdcb892-7152-4032-a402-a9ba267b3b02"),
                            BookDefinitionId = new Guid("a2d0d869-69bb-4d53-8873-25cad510338b"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("04458325-54c3-4f25-b16e-5e8f0fce2562"),
                            BookDefinitionId = new Guid("a5856006-2bac-42d3-a60c-cb5f39715a19"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("e8744ae4-f299-4ff8-ada8-e23f90845ec3"),
                            BookDefinitionId = new Guid("80ef7321-b0a3-4453-b1ba-6e3ecf1b0d0e"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("eeec2a56-72c0-46c1-8b3b-e61450030ead"),
                            BookDefinitionId = new Guid("80ef7321-b0a3-4453-b1ba-6e3ecf1b0d0e"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d6946216-8d7c-47d0-b272-d780d3b033dc"),
                            BookDefinitionId = new Guid("b6fda587-5512-4ccc-9294-5e52c7390773"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a9ef1d77-4272-49b4-aa5b-77a0b0dbee80"),
                            BookDefinitionId = new Guid("e1a08da5-0c3e-4f4c-8f75-3fde7ef6c9b7"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("7006ca97-25b0-4d67-a7a4-b91bc6fc4d16"),
                            BookDefinitionId = new Guid("7cc4c6a6-cbab-4105-a8a6-c100e5c85d67"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("53e62ef4-f0fe-419b-8e02-34f920862cbb"),
                            BookDefinitionId = new Guid("b7d20548-b9fa-4ffe-9166-5b42308864a1"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("b9ff10df-1674-4c96-8a0b-2c6a5790f58a"),
                            BookDefinitionId = new Guid("e1a08da5-0c3e-4f4c-8f75-3fde7ef6c9b7"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("3dedc88b-8f8b-403e-9468-e782adfe22ef"),
                            BookDefinitionId = new Guid("326b3b91-ecd4-48bd-bddb-3fd788d6ea6a"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("c2c0d065-3029-4971-ac6b-4bd326256bbe"),
                            BookDefinitionId = new Guid("cf5c7384-0cac-448b-bec1-c4f3eb3769f0"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("30dc1b8c-6f90-48ba-8434-dcd5be4d8276"),
                            BookDefinitionId = new Guid("7132bc9d-aec5-419a-8594-a427b49a0393"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("ce1cd65c-8361-47d1-84c7-f96e6fbc3ed3"),
                            BookDefinitionId = new Guid("18b3eeac-a9e1-4098-a094-d9cf9df885df"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("7d977b68-ea78-4217-b6a4-a16afdc6b18c"),
                            BookDefinitionId = new Guid("326b3b91-ecd4-48bd-bddb-3fd788d6ea6a"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("e8377740-6ec2-43fd-8ee8-70508351a088"),
                            BookDefinitionId = new Guid("b6fda587-5512-4ccc-9294-5e52c7390773"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("52f38433-da32-445e-aeed-769c21c5e6de"),
                            BookDefinitionId = new Guid("4d25c8c0-e068-40c7-b316-6acba16c261d"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("2bafac4d-096e-493a-be81-b862350189e7"),
                            BookDefinitionId = new Guid("18b3eeac-a9e1-4098-a094-d9cf9df885df"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3550d8b6-c72e-47a8-bf8c-3982f945105d"),
                            BookDefinitionId = new Guid("01ac681a-b52e-45cb-8b81-182d1cda3520"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d77275d7-fc21-4288-b44b-28d845cc4a75"),
                            BookDefinitionId = new Guid("ff1ead80-59eb-4049-b0f8-a71d3911dbd5"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("e120d5f1-f62d-41ad-bbe9-b3b482575115"),
                            BookDefinitionId = new Guid("2ba37673-a6e9-4539-9f68-24921544db84"),
                            Status = 2
                        });
                });

            modelBuilder.Entity("LibSys.Models.Entities.BookDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1a08da5-0c3e-4f4c-8f75-3fde7ef6c9b7"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Kamień Filozoficzny"
                        },
                        new
                        {
                            Id = new Guid("cf5c7384-0cac-448b-bec1-c4f3eb3769f0"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Komnata Tajemnic"
                        },
                        new
                        {
                            Id = new Guid("7132bc9d-aec5-419a-8594-a427b49a0393"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i więzień Azkabanu"
                        },
                        new
                        {
                            Id = new Guid("18b3eeac-a9e1-4098-a094-d9cf9df885df"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Czara Ognia"
                        },
                        new
                        {
                            Id = new Guid("0d0f72a9-d358-4283-aca5-15811ed0aeb8"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Zakon Feniksa"
                        },
                        new
                        {
                            Id = new Guid("0a097611-ce71-4a35-8b70-e3e855a70ae7"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Książę Półkrwi"
                        },
                        new
                        {
                            Id = new Guid("326b3b91-ecd4-48bd-bddb-3fd788d6ea6a"),
                            Author = "Stieg Larsson",
                            Title = "Mężczyźni, którzy nienawidzą kobiet"
                        },
                        new
                        {
                            Id = new Guid("3e0d0ba3-8d04-4700-91bf-f3e3d78129ef"),
                            Author = "George R.R. Martin",
                            Title = "Gra o tron (edycja ilustrowana)"
                        },
                        new
                        {
                            Id = new Guid("8aa0f520-e3aa-4838-b4b8-54b3fda386a3"),
                            Author = "William Shakespeare",
                            Title = "Romeo i Julia"
                        },
                        new
                        {
                            Id = new Guid("a2d0d869-69bb-4d53-8873-25cad510338b"),
                            Author = "George R.R. Martin",
                            Title = "Starcie królów (edycja ilustrowana)"
                        },
                        new
                        {
                            Id = new Guid("8710dd3c-1f39-4f82-80ee-b098c7c5b3c1"),
                            Author = "Camilla Läckberg",
                            Title = "Księżniczka z lodu"
                        },
                        new
                        {
                            Id = new Guid("a5856006-2bac-42d3-a60c-cb5f39715a19"),
                            Author = "George R.R. Martin",
                            Title = "Nawałnica mieczy: Stal i śnieg"
                        },
                        new
                        {
                            Id = new Guid("7921061d-840c-4a56-8b1f-841f7390edc8"),
                            Author = "Johann Wolfgang von Goethe",
                            Title = "Cierpienia młodego Wertera"
                        },
                        new
                        {
                            Id = new Guid("c687f724-506d-448b-9511-e686b91f3dda"),
                            Author = "Veronica Roth",
                            Title = "Niezgodna"
                        },
                        new
                        {
                            Id = new Guid("b7d20548-b9fa-4ffe-9166-5b42308864a1"),
                            Author = "J.K. Rowling, Jack Thorne",
                            Title = "Harry Potter i Przeklęte Dziecko"
                        },
                        new
                        {
                            Id = new Guid("08c709c9-0d6e-4c5c-9b91-77f039dfdb51"),
                            Author = "Juliusz Słowacki",
                            Title = "Balladyna"
                        },
                        new
                        {
                            Id = new Guid("baff91b9-a58d-4e3c-a938-3fd293b432ed"),
                            Author = "Camilla Läckberg",
                            Title = "Kaznodzieja"
                        },
                        new
                        {
                            Id = new Guid("bcecb84c-9f01-4325-b721-9326fb96f2d7"),
                            Author = "Dan Brown",
                            Title = "Inferno"
                        },
                        new
                        {
                            Id = new Guid("c72c0bbb-32eb-4676-a628-2b1aea7e434b"),
                            Author = "Stanisław Wyspiański",
                            Title = "Wesele"
                        },
                        new
                        {
                            Id = new Guid("ff1ead80-59eb-4049-b0f8-a71d3911dbd5"),
                            Author = "Camilla Läckberg",
                            Title = "Kamieniarz"
                        },
                        new
                        {
                            Id = new Guid("b6fda587-5512-4ccc-9294-5e52c7390773"),
                            Author = "Jo Nesbø",
                            Title = "Człowiek nietoperz"
                        },
                        new
                        {
                            Id = new Guid("2eb18b3a-eb70-4984-b20e-eba3082dd5c3"),
                            Author = "Juliusz Słowacki",
                            Title = "Kordian"
                        },
                        new
                        {
                            Id = new Guid("37d737e5-6bc1-40a2-a8c6-b34564d48412"),
                            Author = "Andrzej Sapkowski",
                            Title = "Narrenturm"
                        },
                        new
                        {
                            Id = new Guid("2ba37673-a6e9-4539-9f68-24921544db84"),
                            Author = "Kornel Makuszyński",
                            Title = "Szatan z siódmej klasy"
                        },
                        new
                        {
                            Id = new Guid("01ac681a-b52e-45cb-8b81-182d1cda3520"),
                            Author = "Camilla Läckberg",
                            Title = "Ofiara losu"
                        },
                        new
                        {
                            Id = new Guid("7cc4c6a6-cbab-4105-a8a6-c100e5c85d67"),
                            Author = "Cassandra Clare",
                            Title = "Miasto upadłych aniołów"
                        },
                        new
                        {
                            Id = new Guid("80ef7321-b0a3-4453-b1ba-6e3ecf1b0d0e"),
                            Author = "Camilla Läckberg",
                            Title = "Niemiecki bękart"
                        },
                        new
                        {
                            Id = new Guid("4f15eadc-b2e9-4ac8-b7c5-af8f383105ef"),
                            Author = "Władysław Stanisław Reymont",
                            Title = "Chłopi"
                        },
                        new
                        {
                            Id = new Guid("512a64d4-2940-4897-b202-cb519ece9f19"),
                            Author = "Andrzej Ziemiański",
                            Title = "Achaja. Tom I"
                        },
                        new
                        {
                            Id = new Guid("4d25c8c0-e068-40c7-b316-6acba16c261d"),
                            Author = "Christopher Paolini",
                            Title = "Dziedzictwo"
                        });
                });

            modelBuilder.Entity("LibSys.Models.Entities.Borrowing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ReaderId");

                    b.ToTable("Borrowings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6cf8901a-ea30-445b-a1aa-b2b1e5a6e98a"),
                            BookId = new Guid("6c3cc738-65cc-4c63-9cfd-8bdcae010a84"),
                            BorrowDate = new DateTime(2023, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("115deabf-638d-486c-bbab-ec0455efa5d3"),
                            BookId = new Guid("21c536c4-494c-44f1-84c5-be8fe6145b58"),
                            BorrowDate = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("6df44fe1-0f6a-4dad-b679-0d9f74ae70b1"),
                            BookId = new Guid("a4263179-198f-471a-b7f5-747e2aa05c50"),
                            BorrowDate = new DateTime(2023, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("b757d55d-529d-4cc8-89ae-82036564055e"),
                            ReturnDate = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("a4d17889-a4b3-40c9-a5d1-fc61b6717785"),
                            BookId = new Guid("9aa721a3-8746-43c9-b1eb-6476d2dacacc"),
                            BorrowDate = new DateTime(2023, 12, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("7f3613da-8b4f-4878-bf93-ffc15f0e06d3"),
                            BookId = new Guid("20ec3e8b-8c3b-4dee-9da7-093579c71a4f"),
                            BorrowDate = new DateTime(2023, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("b757d55d-529d-4cc8-89ae-82036564055e"),
                            ReturnDate = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("cda706c8-5201-4206-ab81-f107eab02844"),
                            BookId = new Guid("85c515c7-3ae7-4845-b5ab-043eb413bd22"),
                            BorrowDate = new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("77cff022-1465-49ac-820c-aa5c1ea1b19e"),
                            ReturnDate = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("4ef8dc2d-7f9a-4c36-b3fe-257b26d8621f"),
                            BookId = new Guid("1102a15c-bc66-4291-ac12-8069ef385393"),
                            BorrowDate = new DateTime(2023, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("77cff022-1465-49ac-820c-aa5c1ea1b19e"),
                            ReturnDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("2e818f47-8877-441e-825c-27898feeda23"),
                            BookId = new Guid("78587f17-5dec-4ae4-b4f0-216b0e1866ed"),
                            BorrowDate = new DateTime(2023, 12, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("77cff022-1465-49ac-820c-aa5c1ea1b19e"),
                            ReturnDate = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("b3f3c7bf-a153-4c02-b8ab-e498e142523f"),
                            BookId = new Guid("e29817aa-3989-4831-903b-450f638e174e"),
                            BorrowDate = new DateTime(2023, 12, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6a7de3bb-97f4-4a14-b64f-9fc8a8a8b242"),
                            ReturnDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("5b8dea20-072e-45c8-b753-07cbd6f70f13"),
                            BookId = new Guid("80c3cac4-9b75-431f-93dd-12b3e480281d"),
                            BorrowDate = new DateTime(2023, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("904038c7-5b75-4c6f-aa69-ed2b15d0d3e3"),
                            BookId = new Guid("a908b462-f860-42eb-aba6-f1cbbaab0989"),
                            BorrowDate = new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6a7de3bb-97f4-4a14-b64f-9fc8a8a8b242"),
                            ReturnDate = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("8d0dea4d-196c-4896-b64a-f0db40456284"),
                            BookId = new Guid("079638cb-6d07-4ad6-963f-56cfccee80c7"),
                            BorrowDate = new DateTime(2023, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("3a545999-e75b-4669-8efd-d9d0efe00964"),
                            BookId = new Guid("8600bd80-5d2f-4a26-93c9-8ad950b4f87e"),
                            BorrowDate = new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("255062c4-802b-42d2-b56e-a8ce547a9916"),
                            BookId = new Guid("1ca457bb-65a3-4368-87a7-cfb4c60fb149"),
                            BorrowDate = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("77cff022-1465-49ac-820c-aa5c1ea1b19e"),
                            ReturnDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("e1a1f9af-dc08-4366-a216-9e06cd0d891c"),
                            BookId = new Guid("b64e0711-4ac0-4cf9-aa4d-9e5d2e6167ac"),
                            BorrowDate = new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("b757d55d-529d-4cc8-89ae-82036564055e"),
                            ReturnDate = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("853ceaeb-dcdc-4195-b79c-b5630df37f07"),
                            BookId = new Guid("a77ab981-9426-40c4-8289-735bdca7ef3f"),
                            BorrowDate = new DateTime(2023, 12, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("77cff022-1465-49ac-820c-aa5c1ea1b19e"),
                            ReturnDate = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("b1f26b4a-437d-45ca-98fb-89820a02dd5a"),
                            BookId = new Guid("77b9510b-5310-4a1f-b5ad-3b310fc432ea"),
                            BorrowDate = new DateTime(2023, 12, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("e8974f85-31a8-4569-9422-c694fa0ecc18"),
                            BookId = new Guid("f6cdb6ed-9555-46ba-b8d1-c548c2c9e0ab"),
                            BorrowDate = new DateTime(2023, 12, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("77cff022-1465-49ac-820c-aa5c1ea1b19e"),
                            ReturnDate = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("0fe4a8e2-569f-4cf1-bf79-0469b3a1b1fb"),
                            BookId = new Guid("4746d247-4e52-40e2-8d46-e9c97fd9748d"),
                            BorrowDate = new DateTime(2023, 12, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6a7de3bb-97f4-4a14-b64f-9fc8a8a8b242"),
                            ReturnDate = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("17caf637-4546-4c3f-aa46-d16f5a638818"),
                            BookId = new Guid("16aa5a85-50e6-4b37-b310-1ca8ffabd155"),
                            BorrowDate = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6a7de3bb-97f4-4a14-b64f-9fc8a8a8b242"),
                            ReturnDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("2c762346-63bf-4c24-857c-8ce60239520f"),
                            BookId = new Guid("28e868af-842e-43f2-8a45-447f8e14031c"),
                            BorrowDate = new DateTime(2023, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6a7de3bb-97f4-4a14-b64f-9fc8a8a8b242"),
                            ReturnDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("370afe36-391d-4138-a401-bd4870cdbd06"),
                            BookId = new Guid("86a88a4e-d4aa-44c7-9a56-e0253efc60fc"),
                            BorrowDate = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("39745302-ad15-42df-b432-bc3c16081ea0"),
                            BookId = new Guid("bbc5b71a-f9c8-4bc4-928e-7cf043fbcac5"),
                            BorrowDate = new DateTime(2023, 12, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("09803399-58b7-4fa8-a1a9-c7167b6d3615"),
                            BookId = new Guid("7006ca97-25b0-4d67-a7a4-b91bc6fc4d16"),
                            BorrowDate = new DateTime(2023, 12, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("77cff022-1465-49ac-820c-aa5c1ea1b19e"),
                            ReturnDate = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("1474b77c-c36f-4958-954b-5a34bd490776"),
                            BookId = new Guid("c2c0d065-3029-4971-ac6b-4bd326256bbe"),
                            BorrowDate = new DateTime(2023, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("b757d55d-529d-4cc8-89ae-82036564055e"),
                            ReturnDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("2d826f51-fa20-449e-ac91-cf6a80b767f6"),
                            BookId = new Guid("ce1cd65c-8361-47d1-84c7-f96e6fbc3ed3"),
                            BorrowDate = new DateTime(2023, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("ba6494fa-5df5-4422-a064-0d134f70225a"),
                            BookId = new Guid("7d977b68-ea78-4217-b6a4-a16afdc6b18c"),
                            BorrowDate = new DateTime(2023, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("b757d55d-529d-4cc8-89ae-82036564055e"),
                            ReturnDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("a781913f-969b-4331-808b-1099106e3699"),
                            BookId = new Guid("52f38433-da32-445e-aeed-769c21c5e6de"),
                            BorrowDate = new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("c90959bb-766c-4fd9-8b49-61fbce52b78b"),
                            BookId = new Guid("3550d8b6-c72e-47a8-bf8c-3982f945105d"),
                            BorrowDate = new DateTime(2023, 12, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("77cff022-1465-49ac-820c-aa5c1ea1b19e"),
                            ReturnDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("8d71d320-91e6-46be-b208-8f2672bc4ceb"),
                            BookId = new Guid("d77275d7-fc21-4288-b44b-28d845cc4a75"),
                            BorrowDate = new DateTime(2023, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("77cff022-1465-49ac-820c-aa5c1ea1b19e"),
                            ReturnDate = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("LibSys.Models.Entities.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityChanges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("LibSys.Models.Entities.Reader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Readers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            City = "Poznań",
                            Code = "61-842",
                            Name = "Jan Kowalski",
                            Street = "Za Bramką 12"
                        },
                        new
                        {
                            Id = new Guid("6a7de3bb-97f4-4a14-b64f-9fc8a8a8b242"),
                            City = "Poznań",
                            Code = "61-111",
                            Name = "Tomasz Rydz",
                            Street = "Garbary 1"
                        },
                        new
                        {
                            Id = new Guid("77cff022-1465-49ac-820c-aa5c1ea1b19e"),
                            City = "Poznań",
                            Code = "61-111",
                            Name = "Aleksandra Mechrzycka",
                            Street = "Solna 2"
                        },
                        new
                        {
                            Id = new Guid("b757d55d-529d-4cc8-89ae-82036564055e"),
                            City = "Poznań",
                            Code = "61-311",
                            Name = "Jan Nowak",
                            Street = "Wieżowa 3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b74ddd14-6340-4840-95c2-db12554843e5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eb11eff1-7697-474c-979d-f7ae56a0c530",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEILEvMFJX3gvimmB1QeH3Qf8ttQKgNHTXnSqwo9lDHW2QgFsGNfD+KVpQQIQVZ98og==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5f9c743c-7aaa-4914-a823-0353641e8888",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LibSys.Models.Entities.Book", b =>
                {
                    b.HasOne("LibSys.Models.Entities.BookDefinition", "BookDefinition")
                        .WithMany()
                        .HasForeignKey("BookDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookDefinition");
                });

            modelBuilder.Entity("LibSys.Models.Entities.Borrowing", b =>
                {
                    b.HasOne("LibSys.Models.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibSys.Models.Entities.Reader", "Reader")
                        .WithMany()
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
